name: rubyfmt
description: Ruby Autoformatter!
homepage: https://github.com/fables-tales/rubyfmt
licenses:
  - MIT
languages:
  - Ruby
categories:
  - Formatter
source:
  id: pkg:github/fables-tales/rubyfmt@v0.8.1
  build:
    run: |
      make all
bin:
  rubyfmt: target/release/rubyfmt-main
